name: Frond end main CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  merge-to-main-CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Frond end
        run: |
          yarn global add react-scripts
          yarn install
          yarn build
